# Generated by Django 4.1 on 2024-04-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="main_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="article_main_images"
            ),
        ),
    ]
