# Generated by Django 4.1 on 2024-04-25 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_userlikesarticle"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userlikesarticle",
            old_name="article_id",
            new_name="article",
        ),
        migrations.RenameField(
            model_name="userlikesarticle",
            old_name="user_id",
            new_name="user",
        ),
    ]
