# Generated by Django 4.1 on 2024-04-25 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_rename_article_id_userlikesarticle_article_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="like_counter",
            new_name="like_count",
        ),
    ]
