# Generated by Django 4.1 on 2024-04-26 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0006_thread_threadmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="thread",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="articles.thread",
            ),
        ),
    ]
