# Generated by Django 4.1 on 2024-05-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0008_usersavesarticle_delete_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="category_image",
            field=models.ImageField(blank=True, null=True, upload_to="category_images"),
        ),
    ]
